server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://localhost:8081
          predicates:
            - Path=/bookings/** /bookingLists/**
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/** 
        - id: seat
          uri: http://localhost:8084
          predicates:
            - Path=/seats/**
        - id: promotion
            uri: http://localhost:8085
            predicates:
              - Path=/promotions/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://booking:8080
          predicates:
            - Path=/bookings/** /bookingLists/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/** 
        - id: seat
          uri: http://seat:8080
          predicates:
            - Path=/seats/**
        - id: promotion
            uri: http://promotion:8080
            predicates:
              - Path=/promotions/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
